### ISSUE TITLE
y-z plane selects upside-down

### ISSUE THREAD

**Issue by matze** [ufo-kit/nova#16]
The y-z zoom plane is a bit misleading. Selecting the upper part zooms in the lower and vice versa but should in fact match.

![select](https://user-images.githubusercontent.com/115270/38794623-103e11f6-4156-11e8-90c1-a062237420fb.png)

**Comment by agu3010** [comment]
It was originally like that, but the dragging and resizing were not informative enough, therefore we added coordinates and reversed it. Once we add images to these boxes along with the guidelines we can fix this as well.
