### ISSUE TITLE
Guidelines for zooming

### ISSUE THREAD

**Issue by matze** [ufo-kit/nova#17]
Right now, it's pretty fiddly to position the zoom box correctly mostly because the 3D view can be aligned arbitrarily. Mentally mapping the 2D views gets difficult but could be made a bit simpler by adding guidelines to both the 2D and 3D views similar to how Blender visualizes object translations. See this sketch how it could look like:

![guidelines](https://user-images.githubusercontent.com/115270/38799214-1fbdc42e-4164-11e8-8eda-712978c2e2ee.png)

Bonus points for restricting the translation to one axis by keeping a key pressed.

**Comment by agu3010** [comment]
I can try this out, but it could take some time, as this would mean changes to Wave as well. I'm going to finish up rest of the issues first and then give this some time later today.
